[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'killall -SIGUSR2 waybar'

[templates.niri]
input_path = './templates/niri.kdl'
output_path = '~/.config/niri/colors.kdl'

