[mgr]
show_hidden = true

[opener]
edit = [
    { run = 'nvim "$@"', block = true },
]

img = [
    { run = 'swayimg "$@"' },
]

vid = [
    { run = 'vlc "$@"' },
]

browser = [
    { run = 'librewolf "$@"' },
]

torrent = [
    { run = 'qbittorrent "$@"' },
]

[open]
prepend_rules = [
    { name = "*.png", use = "img" },
    { name = "*.jpg", use = "img" },
    { name = "*.jxl", use = "img" },
    { name = "*.mkv", use = "vid" },
    { name = "*.mp4", use = "vid" },
    { name = "*.pdf", use = "browser" },
    { name = "*.torrent", use = "torrent" },
]
